name: rindti
channels:
  - bioconda
  - pytorch
  - nvidia
  - defaults
  - kalininalab
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohappyeyeballs=2.4.2
  - aiohttp=3.10.8
  - aiosignal=1.3.1
  - amply=0.1.6
  - appdirs=1.4.4
  - async-timeout=4.0.3
  - attmap=0.13.2
  - attrs=24.2.0
  - bcrypt=4.2.0
  - blas=1.0
  - boto3=1.35.29
  - botocore=1.35.29
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.3
  - coin-or-clp=1.17.6
  - coin-or-osi=0.108.6
  - coin-or-utils=2.11.4
  - coincbc=2.10.12
  - colorama=0.4.6
  - configargparse=1.7
  - connection_pool=0.0.3
  - cryptography=43.0.1
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.0
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.68
  - cuda-runtime=12.4.0
  - cuda-version=12.6
  - datrie=0.8.2
  - defusedxml=0.7.1
  - docutils=0.21.2
  - dpath=2.2.0
  - dropbox=12.0.2
  - eido=0.2.2
  - exceptiongroup=1.2.2
  - ffmpeg=4.3
  - filechunkio=1.8
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - ftputil=5.1.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-api-core=2.20.0
  - google-api-python-client=2.147.0
  - google-auth=2.35.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.18.2
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.65.0
  - grpcio=1.62.2
  - httplib2=0.22.0
  - humanfriendly=10.0
  - idna=3.7
  - importlib_resources=6.4.5
  - iniconfig=2.0.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.4.2.65
  - libcufft=11.2.0.44
  - libcufile=1.11.1.6
  - libcurand=10.3.7.68
  - libcusolver=11.6.0.99
  - libcusparse=12.3.0.142
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.2.5.2
  - libnvfatbin=12.6.68
  - libnvjitlink=12.4.99
  - libnvjpeg=12.3.1.89
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.20
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - logmuse=0.2.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - mdurl=0.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.1.0
  - nbformat=5.10.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - oauth2client=4.1.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - paramiko=3.5.0
  - peppy=0.40.6
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - ply=3.11
  - prettytable=3.11.0
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pulp=2.7.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pynacl=1.5.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.4
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=8.3.3
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-irodsclient=2.1.0
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - reretry=0.11.8
  - rich=13.8.1
  - rpds-py=0.20.0
  - rsa=4.9
  - s3transfer=0.10.2
  - setuptools=75.1.0
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=7.0.4
  - smmap=5.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - sqlite=3.45.3
  - stone=3.3.2
  - stopit=1.1.2
  - sympy=1.13.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - throttler=1.2.2
  - tk=8.6.14
  - tomli=2.0.1
  - toposort=1.10
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ubiquerg=0.8.0
  - uritemplate=4.1.1
  - urllib3=1.26.19
  - veracitools=0.1.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - wrapt=1.16.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.13.1
  - yte=1.5.4
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - beautifulsoup4==4.12.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - fuzzywuzzy==0.18.0
      - gdown==5.2.0
      - glycowork==1.3.0
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - jsonargparse==4.7.3
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.7
      - markdown==3.7
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mpld3==0.5.10
      - nvidia-nccl-cu12==2.23.4
      - patsy==0.5.6
      - pytdc==0.3.6
      - pytorch-lightning==2.4.0
      - rdkit==2024.3.5
      - regex==2024.9.11
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - soupsieve==2.6
      - statsmodels==0.14.3
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - torch-geometric==2.6.1
      - torchmetrics==1.4.2
      - tqdm==4.66.5
      - werkzeug==3.1.3
      - xgboost==2.1.1

