seed: 42
runs: 1
exp_name: glassrep2

datamodule:
  filename: datasets/glass/results/prepare_all/wdlnanronr_37af5b7a.pkl
  exp_name: hopium2
  batch_size: 512
  num_workers: 4

trainer:
  devices: 1
  max_epochs: 1000
  profiler: null

early_stop:
  patience: 200

checkpoints:
  monitor: val_loss
  save_top_k: 2
  mode: min

model:
  monitor: val_loss
  module: reg
  feat_method: concat

  # Drug (Ligand) Configuration
  drug:
    method: graph
    hidden_dim: 256
    node:
      module: gatconv
      dropout: 0.1
      hidden_dim: 256
      num_heads: 4
      num_layers: 3
    pool:
      module: mean
      hidden_dim: 256
      num_heads: 4

  # Protein Configuration
  prot:
    method: graph
    hidden_dim: 256
    node:
      module: gatconv
      dropout: 0.1
      hidden_dim: 256
      num_heads: 4
      num_layers: 3
    pool:
      module: mean
      hidden_dim: 256
      num_heads: 4

  
  mlp:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.2

  optimizer:
    module: adam
    lr: 0.0001
    prot_lr: 0.0001
    drug_lr: 0.0001
    weight_decay: 0.01
    momentum: 0.01
    reduce_lr:
      factor: 0.1
      patience: 20
